services:
  postgresql:
    image: postgres:18.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: device-monitoring-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  device-1:
    build:
      context: .
      dockerfile: apps/device-emulator/Dockerfile
    environment:
      DEVICE_ID: device-1
      SUPPORTS_GRPC: "false"
      UNSTABLE_MODE: "false"
    ports:
      - "4001:3000"

  device-2:
    build:
      context: .
      dockerfile: apps/device-emulator/Dockerfile
    environment:
      DEVICE_ID: device-2
      SUPPORTS_GRPC: "true"
      UNSTABLE_MODE: "false"
    ports:
      - "4002:3000"

  device-3:
    build:
      context: .
      dockerfile: apps/device-emulator/Dockerfile
    environment:
      DEVICE_ID: device-3
      SUPPORTS_GRPC: "false"
      UNSTABLE_MODE: "false"
    ports:
      - "4003:3000"

  device-4:
    build:
      context: .
      dockerfile: apps/device-emulator/Dockerfile
    environment:
      DEVICE_ID: device-4
      SUPPORTS_GRPC: "false"
      UNSTABLE_MODE: "true"
    ports:
      - "4004:3000"

  monitoring-service:
    build:
      context: .
      dockerfile: apps/monitoring-service/Dockerfile
    depends_on:
      postgresql:
        condition: service_healthy
      device-1:
        condition: service_started
      device-2:
        condition: service_started
      device-3:
        condition: service_started
      device-4:
        condition: service_started
    environment:
      PORT: 3000
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}
      DEVICES_QTY: 4
      MAX_RETRIES: 3
      TIMEOUT_MS: 2000
      INTERVAL_MS: 30000
    ports:
      - "3000:3000"

volumes:
  db_data:
